cd /d %~dp0
regsvr32.exe  SemCoreCtrlPanel_Stand1.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand2.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand3.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand4.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand5.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand6.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand7.ocx /s
regsvr32.exe  SemCoreCtrlPanel_Stand9.ocx /s
regsvr32.exe  SemCoreCtrlPanel_StandA.ocx /s
